application:
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  showVersionNumber: false
  showGitHubLinks: false
  localBackupEnabled: false
  welcomeBanner:
    showOnFirstStart: false
challenges:
  showHints: false
  safetyOverride: true
  showFeedbackButtons: false
hackingInstructor:
  isEnabled: false
ctf:
  showFlagsInNotifications: true

set NODE_ENV=ctf     # on Windows
export NODE_ENV=ctf  # on Linux

npm start
